pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE = "wissal93/student-management:1.0"
    }
    
    stages {
        stage('Test Docker First') {
            steps {
                script {
                    // Test DIRECT de Docker
                    sh '''
                        echo "=== TEST DOCKER ==="
                        which docker
                        docker --version
                        echo "Docker test: OK"
                    '''
                }
            }
        }
        
        stage('Checkout') {
            steps {
                git 'https://github.com/WissalMonastiri/student-management.git'
            }
        }
        
        stage('Build App') {
            steps {
                dir('student-management') {
                    sh '''
                        ./mvnw clean package -DskipTests
                        echo "Build Java OK"
                    '''
                }
            }
        }
        
        stage('Build Docker') {
            steps {
                dir('student-management') {
                    sh '''
                        docker build -t wissal93/student-management:1.0 .
                        echo "Docker build OK"
                    '''
                }
            }
        }
    }
    
    post {
        success {
            echo '✅ SUCCÈS!'
        }
        failure {
            echo '❌ ÉCHEC'
        }
    }
}
