pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE = "wissal93/student-management:1.0"
    }
    
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/WissalMonastiri/student-management.git'
            }
        }
        
        stage('Build') {
            steps {
                sh '''
                    chmod +x mvnw
                    ./mvnw clean package -DskipTests
                '''
            }
        }
        
        stage('Build Docker') {
            steps {
                sh """
                    docker build -t ${DOCKER_IMAGE} .
                    echo "Image créée:"
                    docker images | grep wissal93/student-management
                """
            }
        }
        
        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-credentials',
                    usernameVariable: 'USERNAME',
                    passwordVariable: 'PASSWORD'
                )]) {
                    sh """
                        echo \$PASSWORD | docker login -u \$USERNAME --password-stdin
                        docker push ${DOCKER_IMAGE}
                        docker logout
                    """
                }
            }
        }
    }
    
    post {
        success {
            echo "✅ Image ${DOCKER_IMAGE} poussée avec succès sur Docker Hub!"
        }
        failure {
            echo "❌ La pipeline a échoué"
        }
    }
}
